/*C
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entities.Annee;
import Entities.Etudiant;
import Entities.Grade;
import Entities.Institut;
import Entities.Semestre;
import com.toedter.calendar.JCalendar;
import database.AnneeDAO;
import database.Connexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import database.EtudiantDAO;
import database.GradeDAO;
import database.InstitutDAO;
import database.SemestreDAO;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Carlos SMY
 */
public class Ajouter_Etudiant extends javax.swing.JPanel {

    /**
     * Creates new form Ajouter_Etudiant
     */
    public static Connection conn;
    public static PreparedStatement statement;
    public static ResultSet result;
    String  sex;
  
    public Ajouter_Etudiant() throws SQLException {
        initComponents();
        ajout.setText("Ajouter");
        ConnecterGrade(grade);
        ConnecterAnnee(annee);
        ConnecterInstitut(institut);
        ConnecterSemestre(semestre);

        
    }
    public Ajouter_Etudiant(Etudiant et) throws SQLException{
          initComponents();
          
        ConnecterGrade(grade);
        ConnecterAnnee(annee);
        ConnecterInstitut(institut);
        ConnecterSemestre(semestre);
        matricule.setText(et.getMatricule());
        nom.setText(et.getNom());
        prenoms.setText(et.getPrenom());
        naissance.setDate(et.getDate_naissance());
        grade.setSelectedItem(et.getGrade().getLibgrade());
        institut.setSelectedItem(et.getInstitut().getLibinstitut());
        annee.setSelectedItem(et.getAnnee().getLibannee());
        semestre.setSelectedItem(et.getSemestre().getLibsemestre());
        labelTitre.setText("Modifier Etudiant");
        ajout.setText("Modifier");
    }
    public static void refresh() throws SQLException{
        Panneau_Etudiant pan = new Panneau_Etudiant();
        Accueil.moving.add(pan,"etudiant");
        Accueil.card.show(Accueil.moving, "etudiant");
    }   
    public static void ConnecterGrade(JComboBox box) throws SQLException{
        //afficher les resultats du tableau
        conn = Connexion.Connecter();
        String query="SELECT * from grade ";
        statement = conn.prepareStatement(query);
        //statement.setString(1,code);
       result = statement.executeQuery();
        //les ajouter dans le combo box
        while (result.next()) {
            box.addItem(result.getString(2));
        }
  
    }

        public static void ConnecterInstitut(JComboBox box) throws SQLException{
        //afficher les resultats du tableau
        conn = Connexion.Connecter();
        String query="SELECT * from institut ";
        statement = conn.prepareStatement(query);
        //statement.setString(1,code);
       result = statement.executeQuery();
        //les ajouter dans le combo box
        while (result.next()) {
            box.addItem(result.getString(2));
        }
        
    }

            public static void ConnecterAnnee(JComboBox box) throws SQLException{
        //afficher les resultats du tableau
        
        conn = Connexion.Connecter();
        String query="SELECT * from annee ";
        statement = conn.prepareStatement(query);
       // statement.setString(1,code);
       result = statement.executeQuery();
        //les ajouter dans le combo box
        while (result.next()) {
           
            box.addItem(result.getString("numAnnee"));
            
        }
        
        
    }  
   
        public static void ConnecterSemestre(JComboBox box) throws SQLException{
        //afficher les resultats du tableau
        conn = Connexion.Connecter();
        String query="SELECT * from semestre ";
        statement = conn.prepareStatement(query);
       // statement.setString(1,);
       result = statement.executeQuery();
        //les ajouter dans le combo box
        while (result.next()) {
            box.addItem(result.getString(2));
        }     
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonSexe = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        labelTitre = new javax.swing.JLabel();
        labelMatricule = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelPrenom = new javax.swing.JLabel();
        labelNaissance = new javax.swing.JLabel();
        labelSexe = new javax.swing.JLabel();
        labelGrade = new javax.swing.JLabel();
        labelInstitut = new javax.swing.JLabel();
        labelAnnee = new javax.swing.JLabel();
        labelSemestre = new javax.swing.JLabel();
        ajout = new javax.swing.JButton();
        semestre = new javax.swing.JComboBox<>();
        annee = new javax.swing.JComboBox<>();
        institut = new javax.swing.JComboBox<>();
        grade = new javax.swing.JComboBox<>();
        Masculin = new javax.swing.JRadioButton();
        Feminin = new javax.swing.JRadioButton();
        nom = new javax.swing.JTextField();
        matricule = new javax.swing.JTextField();
        test = new javax.swing.JLabel();
        prenoms = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        labelTitre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitre.setForeground(new java.awt.Color(52, 1, 152));
        labelTitre.setText("Ajouter un Etudiant");

        labelMatricule.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelMatricule.setText("Matricule");

        labelNom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNom.setText("Nom");

        labelPrenom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelPrenom.setText("Prénoms");

        labelNaissance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNaissance.setText("Date de naissance");

        labelSexe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSexe.setText("Sexe");

        labelGrade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelGrade.setText("Grade");

        labelInstitut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelInstitut.setText("Institut");

        labelAnnee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelAnnee.setText("Année");

        labelSemestre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSemestre.setText("Semestre");

        ajout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ajout.setText("Ajouter");
        ajout.setToolTipText("Ajout de l'Etudiant");
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutajoutActionPerformed(evt);
            }
        });

        semestre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        semestre.setToolTipText("Selectionner le semestre");

        annee.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        annee.setToolTipText("Selectionner l'Année");

        institut.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        institut.setToolTipText("Selectionner l'institut");

        grade.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        grade.setToolTipText("Selectionner le Grade");

        boutonSexe.add(Masculin);
        Masculin.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Masculin.setText("Homme");
        Masculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinActionPerformed(evt);
            }
        });

        boutonSexe.add(Feminin);
        Feminin.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Feminin.setText("Femme");
        Feminin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemininActionPerformed(evt);
            }
        });

        nom.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomnomActionPerformed(evt);
            }
        });

        matricule.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        prenoms.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        prenoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomsnomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrenom)
                            .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNaissance)
                            .addComponent(labelSexe)
                            .addComponent(labelGrade)
                            .addComponent(labelInstitut)
                            .addComponent(labelAnnee)
                            .addComponent(labelSemestre))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(matricule)
                            .addComponent(nom)
                            .addComponent(prenoms)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(semestre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(annee, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(institut, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(grade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Masculin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addComponent(Feminin))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenoms, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Masculin)
                    .addComponent(Feminin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grade)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelInstitut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(institut)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(annee)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(semestre)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ajout, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void Ajouter(){
        
       int day;
       day= naissance.getDate().getDate();
       int mois=naissance.getDate().getMonth();
       int year=naissance.getDate().getYear();
         Date da=new Date(year, mois, day);
      // test.setText(da.toString());
       
       
       try{
           conn = Connexion.Connecter();
           Grade a = GradeDAO.find(grade.getSelectedItem().toString());
       Institut b = InstitutDAO.find(institut.getSelectedItem().toString());
        Annee c = AnneeDAO.find(annee.getSelectedItem().toString());
       Semestre d = SemestreDAO.find(semestre.getSelectedItem().toString());
        Etudiant et = new Etudiant(matricule.getText(),nom.getText(),prenoms.getText(),sex,da,a,b,c,d);
        EtudiantDAO dao = new EtudiantDAO();
        Panneau_Etudiant.EtudiantListe.add(et);
        dao.insererEtudiant(et);
        
       }catch(SQLException e){
           e.printStackTrace();
           
       }    
    }
    private void Modifier(){
        Etudiant et=Chaque_Etudiant.copie.Copy();
         String mat=et.getMatricule();
       int day= naissance.getDate().getDay();
       int mois=naissance.getDate().getMonth();
       int year=naissance.getDate().getYear();
       Date da=new Date(year, mois, day);
       try{
           conn = Connexion.Connecter();
           Grade a = GradeDAO.find(grade.getSelectedItem().toString());
       Institut b = InstitutDAO.find(institut.getSelectedItem().toString());
        Annee c = AnneeDAO.find(annee.getSelectedItem().toString());
       Semestre d = SemestreDAO.find(semestre.getSelectedItem().toString());
        Etudiant ed = new Etudiant(matricule.getText(),nom.getText(),prenoms.getText(),sex,da,a,b,c,d);
        EtudiantDAO dao = new EtudiantDAO();
        dao.Update(ed,mat);
        
       }catch(SQLException e){
           e.printStackTrace();
           
       }
       
    }
    private void Reset(){
        matricule.setText("");
        nom.setText("");
        prenoms.setText("");   
        naissance.setDate(null);
           
       }
  
    private void ajoutajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutajoutActionPerformed
        // TODO add your handling code here:
     if(ajout.getText().equals("Modifier")){
         Modifier();
         try {
             refresh();
         } catch (SQLException ex) {
             Logger.getLogger(Ajouter_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
         }
         JOptionPane.showMessageDialog(this,"Etudiant bien modifié");
       //  Accueil.card.show(Panneau_Etudiant.moving3, "plus");
         
        
         
     }
     else{
         Ajouter();
         try {
             refresh();
         } catch (SQLException ex) {
             Logger.getLogger(Ajouter_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
         }
         JOptionPane.showMessageDialog(this,"Etudiant bien ajouté");
         
         Reset();
     }
     
     
   
       
      
    }//GEN-LAST:event_ajoutajoutActionPerformed

    private void nomnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomnomActionPerformed

    private void MasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinActionPerformed
        // TODO add your handling code here:
        sex ="M";
    }//GEN-LAST:event_MasculinActionPerformed

    private void FemininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemininActionPerformed
        // TODO add your handling code here:
        sex="F";
    }//GEN-LAST:event_FemininActionPerformed

    private void prenomsnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomsnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomsnomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Feminin;
    private javax.swing.JRadioButton Masculin;
    private javax.swing.JButton ajout;
    private javax.swing.JComboBox<String> annee;
    private javax.swing.ButtonGroup boutonSexe;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JComboBox<String> institut;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel labelAnnee;
    private javax.swing.JLabel labelGrade;
    private javax.swing.JLabel labelInstitut;
    private javax.swing.JLabel labelMatricule;
    private javax.swing.JLabel labelNaissance;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JLabel labelSemestre;
    private javax.swing.JLabel labelSexe;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JTextField matricule;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenoms;
    private javax.swing.JComboBox<String> semestre;
    private javax.swing.JLabel test;
    // End of variables declaration//GEN-END:variables
}
