/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entities.Ecue;
import Entities.UE;
import static Interface.Ajouter_Etudiant.statement;
import database.Connexion;
import database.EcueDAO;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Carlos SMY
 */
public class Chaque_UE extends javax.swing.JPanel {
    Connection conn;
    ResultSet resultat;
    //PreparedStatement statement;
    /**
     * Creates new form Chaque_UE
     */
    public static UE copie;
    public static Ecue del=null;
    public Chaque_UE() {
        initComponents();
       
    }
    public Chaque_UE(UE ues) throws SQLException {
        initComponents();
        copie = ues;
        UE ue;
        ue= copie;
         cardPanel.setLayout(Accueil.card);
        Modifier_UE mo = new Modifier_UE();
        cardPanel.add(mo,"afficher bouton");
        Ajouter_UE ad = new Ajouter_UE(ue);
        cardPanel.add(ad,"modifier");
        niveau.setText(ue.getCode());
        nom.setText(ue.getNom());
        String b=ue.getInstitut().getLibinstitut();
        String c=ue.getAnnee().getLibannee();
        String d = ue.getSemestre().getLibsemestre();
        String niv;
        niv=b+" "+c+" Semestre "+d;
      niveau.setText(niv);
        String query ="SELECT codeEcue ,nom,nbCredit  FROM ecue WHERE UE = ? ";
        conn=Connexion.Connecter();
        statement = conn.prepareStatement(query);
        statement.setString(1, ue.getCode());
        //Affichage(statement);
        newAffichage(statement);
        
    }
    public static void refresh() throws SQLException{
        Chaque_UE pan = new Chaque_UE(copie);
        Accueil.moving.add(pan,"matiere");
        Accueil.card.show(Accueil.moving, "matiere");
    }
       public void Affichage(PreparedStatement statement){
        try{
            resultat = statement.executeQuery();
            tableEcue.setModel(DbUtils.resultSetToTableModel(resultat));
        }catch(Exception e){
            System.out.println("Exception :"+e);
        }
    }
    
           public void newAffichage(PreparedStatement statement) {
        tableEcue.setModel(new javax.swing.table.DefaultTableModel(getinfo(statement), new String[]{"Code", "Nom","Nombre de crédit"}) {
            @Override
            public boolean isCellEditable(int row, int colomn) {
                return false;
            }
        });

    }

    public Object[][] getinfo(PreparedStatement statement) {
        int i = 0;
        int a = 0;
        int b = 1;
        int c = 0;

        Object[][] data = null;

        try {

            resultat = statement.executeQuery();
            //permet d'aller de la première ligne à la dernière ligne
            while (resultat.next()) {
                i++;
            }

            data = new Object[i][3];
            int k = 0;

            resultat.absolute(1);
            //vous positionner avant la première ligne de votre résultat
            resultat.beforeFirst();
            while (resultat.next()) {
                data[k][0] = resultat.getString("codeEcue");
                data[k][1] = resultat.getString("nom");
                data[k][2] = resultat.getString("nbCredit");
                

                k++;

            }

        } catch (SQLException e) {
        }
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        niveau = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEcue = new javax.swing.JTable(){
            public boolean isCellEditable(int d , int c){
                return false;
            }
        };
        recherche = new javax.swing.JTextField();
        boutonRecherche = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        code1 = new javax.swing.JLabel();

        niveau.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        niveau.setText("Niveau");

        nom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nom.setText("Nom");

        tableEcue.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tableEcue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEcue.setRowHeight(22);
        tableEcue.setRowMargin(2);
        tableEcue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEcueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableEcueMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tableEcue);

        boutonRecherche.setText("Recherche");
        boutonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        code1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        code1.setText("Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 621, Short.MAX_VALUE)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(687, Short.MAX_VALUE)
                    .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(boutonRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(683, 683, 683))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(code1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(244, 244, 244)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boutonRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boutonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRechercheActionPerformed
        // TODO add your handling code here:
        String query = "SELECT codeEcue ,nom , nbCreditFROM ecue WHERE UE=? AND codeEcue like ? OR UE=? AND nom like ? ";
        PreparedStatement statement;
       try{ 
           statement= conn.prepareStatement(query);
            String str= "%"+recherche.getText()+"%";
            statement.setString(1,copie.getCode());
            statement.setString(2,str);
            statement.setString(3,copie.getCode());
            statement.setString(4, str);
             Affichage(statement);
       }catch(SQLException ed){
           ed.printStackTrace();
           
       }
    }//GEN-LAST:event_boutonRechercheActionPerformed

    private void tableEcueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEcueMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_tableEcueMouseEntered

    private void tableEcueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEcueMouseClicked
        // TODO add your handling code here:
             int count= evt.getClickCount();
      int row = tableEcue.rowAtPoint(evt.getPoint());
        String code = tableEcue.getValueAt(row, 0).toString();
        EcueDAO dao = new EcueDAO();
        Ecue ue;
     try{
         ue = dao.find(code);;
         if (count==1){
             del=ue;
         }
         if (count>=2){
           
        Chaque_Ecue shaq = new Chaque_Ecue(ue);
           Accueil.moving.add(shaq,"information");
            Accueil.card.show(Accueil.moving,"information");
        
          
      }
     }catch(SQLException e){
         e.printStackTrace();
     }
      
    }//GEN-LAST:event_tableEcueMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonRecherche;
    public static javax.swing.JPanel cardPanel;
    private javax.swing.JLabel code1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel niveau;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField recherche;
    private javax.swing.JTable tableEcue;
    // End of variables declaration//GEN-END:variables
}
