/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.Chaque_Etudiant.copie;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Carlos SMY
 */
public class Impression extends javax.swing.JPanel {

    /**
     * Creates new form Impression
     */
    Connection conn;
    
    public Impression() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Impression");
        jButton1.setToolTipText("Imprimer le relevé d'un Etudiant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          try {
            conn=database.Connexion.Connecter();//on doit declarerune connexion 3
            //Chemin vers le fichier jrxml
            JasperDesign design = JRXmlLoader.load("C:\\Users\\Carlos SMY\\Documents\\NetBeansProjects\\Releve\\Releve.jrxml");
            //onn declare un hashmap pour mettre les paramètres
            HashMap parametre = new HashMap();//2
            //on met les parametres a l'interieur du hashMap, le nom entre doublecoat represente le nom du paramètre dans iReport
            parametre.put("matricule",Panneau_Etudiant.del.getMatricule());
            JasperReport jr = JasperCompileManager.compileReport(design);//1
            JasperPrint jp;
            //sa prend en parametre 1,2 et 3
            jp = JasperFillManager.fillReport(jr, parametre,conn);
            //mettre dans le panel panel impression
            // yoGUI.Impression.removeAll()
            //fini
            //JRViewer view =new JRViewer(jp);ne marche pas ici
            //pour afficher le relevé en dehors de l'appli
            //JasperViewer.viewReport(jp);
            JasperViewer.viewReport(jp);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (JRException ex) {
            Logger.getLogger(Chaque_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Erreur");
        }catch(NullPointerException er){
            JOptionPane.showMessageDialog(this,"Veuillez selectionner un etudiant","Erreur",0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
