/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entities.Etudiant;
import database.EtudiantDAO;
import database.MarkDAO;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos SMY
 */
public class Modifier_Etudiant extends javax.swing.JPanel {

    /**
     * Creates new form Modifier_Etudiant
     */
    Etudiant et = Chaque_Etudiant.copie;
    public Modifier_Etudiant() {
        initComponents();
    }
       private void refresh(Etudiant e) throws SQLException{
         Chaque_Etudiant ch = new Chaque_Etudiant(e);
         Accueil.moving.add(ch,"addd");
         Accueil.card.show(Accueil.moving,"addd");
       }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete = new javax.swing.JButton();
        ajoutNote = new javax.swing.JButton();
        update = new javax.swing.JButton();
        suppressionNote = new javax.swing.JButton();
        modificationNote = new javax.swing.JButton();

        setBackground(new java.awt.Color(152, 0, 1));

        delete.setBackground(new java.awt.Color(52, 1, 152));
        delete.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Supprimer");
        delete.setToolTipText("Supprimer l'Etudiant");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        ajoutNote.setBackground(new java.awt.Color(52, 1, 152));
        ajoutNote.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ajoutNote.setForeground(new java.awt.Color(255, 255, 255));
        ajoutNote.setText("Ajout Note");
        ajoutNote.setToolTipText("Ajouter une note");
        ajoutNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutNoteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutNoteMouseExited(evt);
            }
        });
        ajoutNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutNoteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(52, 1, 152));
        update.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Modifier");
        update.setToolTipText("Modifier les informations sur l'etudiant");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        suppressionNote.setBackground(new java.awt.Color(52, 1, 152));
        suppressionNote.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        suppressionNote.setForeground(new java.awt.Color(255, 255, 255));
        suppressionNote.setText("Suppression Note");
        suppressionNote.setToolTipText("Supprimer une note");
        suppressionNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppressionNoteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppressionNoteMouseExited(evt);
            }
        });
        suppressionNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppressionNoteActionPerformed(evt);
            }
        });

        modificationNote.setBackground(new java.awt.Color(52, 1, 152));
        modificationNote.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        modificationNote.setForeground(new java.awt.Color(255, 255, 255));
        modificationNote.setText("Modification Note");
        modificationNote.setToolTipText("Modifier une note");
        modificationNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificationNoteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificationNoteMouseExited(evt);
            }
        });
        modificationNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(suppressionNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ajoutNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificationNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ajoutNote, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(modificationNote, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suppressionNote, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutNoteActionPerformed
        // TODO add your handling code here:
      
         Ajouter_Note aj;
        try {
            aj = new Ajouter_Note(et);
             Chaque_Etudiant.cardPanel.add(aj,"Ajout Note");
        Accueil.card.show(Chaque_Etudiant.cardPanel,"Ajout Note");
        } catch (SQLException ex) {
            Logger.getLogger(Modifier_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Affichage du panel pour ajouter la note
       
    }//GEN-LAST:event_ajoutNoteActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        EtudiantDAO dao = new EtudiantDAO();
        MarkDAO da = new MarkDAO();
        try {
            da.deletebyEtudiant(et);
            dao.delete(et);
            Panneau_Etudiant pa = new Panneau_Etudiant();
        Accueil.moving.add(pa,"eetude");
        Accueil.card.show(Accueil.moving, "eetude");
        } catch (SQLException ex) {
            Logger.getLogger(Modifier_Etudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_deleteActionPerformed

    private void ajoutNoteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutNoteMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_ajoutNoteMouseExited

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_deleteMouseExited

    private void ajoutNoteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutNoteMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ajoutNoteMouseEntered

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
         this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_deleteMouseEntered

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         Accueil.card.show(Chaque_Etudiant.cardPanel,"modifier");
        
    }//GEN-LAST:event_updateActionPerformed

    private void suppressionNoteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppressionNoteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_suppressionNoteMouseEntered

    private void suppressionNoteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppressionNoteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suppressionNoteMouseExited

    private void suppressionNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppressionNoteActionPerformed
        // TODO add your handling code here:
        try{
            MarkDAO dao = new MarkDAO();
            int o = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer cette note?","Confirmer Suppression", 1);
            if (o==0){
            dao.delete(Chaque_Ecue.del);
            JOptionPane.showMessageDialog(this,"Note bien supprimée", "Suppression réussie", 1);
            refresh(Chaque_Etudiant.copie);
            }
        }catch(SQLException e){
        e.printStackTrace();
        }
        catch(NullPointerException et){
          JOptionPane.showMessageDialog(this,"Veuillez saisir une ligne", "Erreur", 0);  
        }
    }//GEN-LAST:event_suppressionNoteActionPerformed

    private void modificationNoteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificationNoteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificationNoteMouseEntered

    private void modificationNoteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificationNoteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificationNoteMouseExited

    private void modificationNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationNoteActionPerformed
        // TODO add your handling code here:
           try{
          Ajouter_Note ed = new Ajouter_Note(Chaque_Ecue.del);
          Chaque_Etudiant.cardPanel.add(ed,"modifiernote");
          Accueil.card.show(Chaque_Etudiant.cardPanel, "modifiernote");
           
            
        }catch(SQLException e){
        e.printStackTrace();
        }
         catch(NullPointerException et){
          JOptionPane.showMessageDialog(this,"Veuillez saisir une ligne", "Erreur", 0);  
        }
    }//GEN-LAST:event_modificationNoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutNote;
    private javax.swing.JButton delete;
    private javax.swing.JButton modificationNote;
    private javax.swing.JButton suppressionNote;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
