/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import database.MarkDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos SMY
 */
public class Modifier_Note extends javax.swing.JPanel {

    /**
     * Creates new form Modifier_Note
     */
    public Modifier_Note() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suppression = new javax.swing.JButton();
        ajout = new javax.swing.JButton();
        modification = new javax.swing.JButton();

        setBackground(new java.awt.Color(152, 0, 1));

        suppression.setBackground(new java.awt.Color(52, 1, 152));
        suppression.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        suppression.setForeground(new java.awt.Color(255, 255, 255));
        suppression.setText("Supprimer Note");
        suppression.setToolTipText("Supprimer une note dans l'Ecue");
        suppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppressionActionPerformed(evt);
            }
        });

        ajout.setBackground(new java.awt.Color(52, 1, 152));
        ajout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ajout.setForeground(new java.awt.Color(255, 255, 255));
        ajout.setText("Ajouter Note");
        ajout.setToolTipText("Ajouter une note a  'Ecue");
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });

        modification.setBackground(new java.awt.Color(52, 1, 152));
        modification.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modification.setForeground(new java.awt.Color(255, 255, 255));
        modification.setText("Modifier Note");
        modification.setToolTipText("Modifier une note dans l'Ecue");
        modification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suppression, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modification, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(modification, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(suppression, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void suppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppressionActionPerformed
        // TODO add your handling code here:
        try{
            MarkDAO dao = new MarkDAO();
            int o = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment supprimer cette note?","Confirmer Suppression", 1);
            if (o==0){
            dao.delete(Chaque_Ecue.del);
            JOptionPane.showMessageDialog(this,"Note bien supprimée", "Suppression réussie", 1);
            }
        }catch(SQLException e){
        e.printStackTrace();
        }
        catch(NullPointerException et){
          JOptionPane.showMessageDialog(this,"Veuillez saisir une ligne", "Erreur", 0);  
        }
    }//GEN-LAST:event_suppressionActionPerformed

    private void modificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationActionPerformed
        // TODO add your handling code here:
         try{
          Ajouter_Note ed = new Ajouter_Note(Chaque_Ecue.del);
          Chaque_Ecue.cardPanel.add(ed,"modifiernote");
          Accueil.card.show(Chaque_Ecue.cardPanel, "modifiernote");
           
            
        }catch(SQLException e){
        e.printStackTrace();
        }
         catch(NullPointerException et){
          JOptionPane.showMessageDialog(this,"Veuillez saisir une ligne", "Erreur", 0);  
          et.printStackTrace();
        }
    }//GEN-LAST:event_modificationActionPerformed

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
        // TODO add your handling code here:
         try{
          Ajouter_Note ed = new Ajouter_Note(Panneau_Note.del);
          Chaque_Ecue.cardPanel.add(ed,"ajouternote");
          Accueil.card.show(Chaque_Ecue.cardPanel, "ajouternote");
           
            
        }catch(SQLException e){
        e.printStackTrace();
        }
         catch(NullPointerException et){
          JOptionPane.showMessageDialog(this,"Veuillez saisir une ligne", "Erreur", 0);  
        }
        
        
    }//GEN-LAST:event_ajoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajout;
    private javax.swing.JButton modification;
    private javax.swing.JButton suppression;
    // End of variables declaration//GEN-END:variables
}
