/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entities.Ecue;
import Entities.Note;
import database.Connexion;
import database.EcueDAO;
import database.NoteDAO;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import net.proteanit.sql.DbUtils;

/**
 *
 * @author Carlos SMY
 */
public class Panneau_Note extends javax.swing.JPanel {

    /**
     * Creates new form Panneau_Note
     */
  public static Ecue del;
         Connection conn;
    PreparedStatement statement;
    ResultSet resultat;
    
    public Panneau_Note() throws SQLException {
        initComponents();
        moving4.setLayout(Accueil.card);
        PanelPlus3 nel= new PanelPlus3();
        moving4.add(nel,"add");
        Ajouter_Note no = new Ajouter_Note();
        moving4.add(no,"ajouter");
        //Requète d'affichage
        String query = "SELECT codeEcue,nom,nbCredit,nomUE as UE "
                + "FROM ecue,ue "
                + "WHERE  ue.codeUE=ecue.UE ";
        conn=Connexion.Connecter();
        statement=conn.prepareStatement(query);
        newAffichage(statement);
        
        
        
    }
      public void newAffichage(PreparedStatement statement){
        TableNote.setModel(new javax.swing.table.DefaultTableModel(getinfo(statement),new String[]{"Code Ecue", "Nom", "Credit", "UE"}) {
                    @Override
                    public boolean isCellEditable(int row, int colomn) {
                        return false;
                    }
                });
              
    }

      public Object[][] getinfo(PreparedStatement statement) {
        int i = 0;
        int a = 0;
        int b = 1;
        int c = 0;

        Object[][] data = null;

        try {
           
           resultat=statement.executeQuery();
            //permet d'aller de la première ligne à la dernière ligne
            while (resultat.next()) {
                i++;
            }

            data = new Object[i][4];
            int k = 0;

            resultat.absolute(1);
            //vous positionner avant la première ligne de votre résultat
            resultat.beforeFirst();
            while (resultat.next()) {
                data[k][0] = resultat.getString("codeEcue");
                data[k][1] = resultat.getString("nom");
                data[k][2] = resultat.getString("nbCredit");
                data[k][3] = resultat.getString("UE");
               
                
                k++;

            }

        } catch (SQLException e) {
        }
        return data;
    }
        public void Affichage(PreparedStatement statement){
        try{
            resultat = statement.executeQuery();
            TableNote.setModel(DbUtils.resultSetToTableModel(resultat));
        }catch(Exception e){
            System.out.println("Exception :"+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNote = new javax.swing.JLabel();
        TextField_rechercher = new javax.swing.JTextField();
        Bouton_Rechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNote = new javax.swing.JTable();
        moving4 = new javax.swing.JPanel();

        labelNote.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelNote.setText("Notes");

        Bouton_Rechercher.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Bouton_Rechercher.setText("Rechercher");
        Bouton_Rechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_RechercherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bouton_RechercherMouseExited(evt);
            }
        });
        Bouton_Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_RechercherActionPerformed(evt);
            }
        });

        TableNote.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TableNote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Prénom", "Sexe"
            }
        ));
        TableNote.setGridColor(new java.awt.Color(255, 255, 255));
        TableNote.setRowHeight(22);
        TableNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNoteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableNoteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TableNoteMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(TableNote);

        javax.swing.GroupLayout moving4Layout = new javax.swing.GroupLayout(moving4);
        moving4.setLayout(moving4Layout);
        moving4Layout.setHorizontalGroup(
            moving4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        moving4Layout.setVerticalGroup(
            moving4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1861, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(labelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(Bouton_Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                    .addComponent(moving4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(moving4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextField_rechercher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Bouton_Rechercher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(1, 1, 1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_RechercherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_RechercherMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Bouton_RechercherMouseEntered

    private void Bouton_RechercherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_RechercherMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Bouton_RechercherMouseExited

    private void Bouton_RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_RechercherActionPerformed
        // TODO add your handling code here:
        String query = "SELECT codeEcue,nom,nbCredit,nomUE "
        + " FROM  ecue,ue "
        + "WHERE ue.codeUE=ecue.UE AND codeEcue like ? OR  ue.codeUE=ecue.UE AND nom like ? ";
        PreparedStatement statement;
        try{
            statement= conn.prepareStatement(query);
            String str= "%"+TextField_rechercher.getText()+"%";
            statement.setString(1,str);
            statement.setString(2,str);
            Affichage(statement);
        }catch(SQLException ed){
            ed.getMessage();

        }

    }//GEN-LAST:event_Bouton_RechercherActionPerformed

    private void TableNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNoteMouseClicked
        // TODO add your handling code here:
        
        int count= evt.getClickCount();
        int row = TableNote.rowAtPoint(evt.getPoint());
        String code= TableNote.getValueAt(row, 0).toString();
        EcueDAO dao = new EcueDAO();
        Ecue no;
        try{
            no = dao.find(code);
            if (count==1){
                del=no;
            }
            if (count>=2){
               
                Chaque_Ecue shaq = new Chaque_Ecue(no);
                Accueil.moving.add(shaq,"information");
                Accueil.card.show(Accueil.moving,"information");

            }
        }catch(SQLException e){
            e.printStackTrace();
        }


    }//GEN-LAST:event_TableNoteMouseClicked

    private void TableNoteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNoteMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_TableNoteMouseEntered

    private void TableNoteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNoteMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_TableNoteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_Rechercher;
    private javax.swing.JTable TableNote;
    private javax.swing.JTextField TextField_rechercher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNote;
    public static javax.swing.JPanel moving4;
    // End of variables declaration//GEN-END:variables
}
