/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entities.UE;
import database.Connexion;
import database.UesDAO;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.naming.spi.DirStateFactory.Result;
//import net.proteanit.sql.DbUtils;

/**
 *
 * @author Carlos SMY
 */
public class Panneau_UE extends javax.swing.JPanel {

    /**
     * Creates new form Panneau_UE
     */
    Connection conn;
    PreparedStatement statement;
    ResultSet resultat;
    public static UE del;

    public Panneau_UE() throws SQLException {

        conn = Connexion.Connecter();
        initComponents();
        moving2.setLayout(Accueil.card);
        //declaration des panels a ajouter dans moving2
        PanelPlus plus = new PanelPlus();
        Ajouter_UE aj = new Ajouter_UE();
        moving2.add(plus, "plus");
       // moving2.add(aj, "panelAdd");
        String query = "SELECT codeUE AS code,nomUE AS nom,nomInstitut AS institut,numAnnee AS annee,numSemestre AS semestre  "
                + "FROM ue,institut,annee,semestre "
                + "WHERE ue.idInstitut=institut.id AND ue.idAnnee=annee.id AND ue.idSemestre=semestre.id ";
        statement = conn.prepareStatement(query);
        //Affichage(statement);
        newAffichage(statement);

    }
      public static void refresh() throws SQLException{
       Panneau_UE pan = new Panneau_UE();
        Accueil.moving.add(pan,"matiere");
        Accueil.card.show(Accueil.moving, "matiere");
      
    } 

    public void Affichage(PreparedStatement statement) {
        try {
            resultat = statement.executeQuery();
            TableUE.setModel(DbUtils.resultSetToTableModel(resultat));
        } catch (Exception e) {
            System.out.println("Exception :" + e);
        }

    }

    public void newAffichage(PreparedStatement statement) {
        TableUE.setModel(new javax.swing.table.DefaultTableModel(getinfo(statement), new String[]{"Code", "Nom", "Institut", "Annee", "Semestre"}) {
            @Override
            public boolean isCellEditable(int row, int colomn) {
                return false;
            }
        });

    }

    public Object[][] getinfo(PreparedStatement statement) {
        int i = 0;
        int a = 0;
        int b = 1;
        int c = 0;

        Object[][] data = null;

        try {

            resultat = statement.executeQuery();
            //permet d'aller de la première ligne à la dernière ligne
            while (resultat.next()) {
                i++;
            }

            data = new Object[i][5];
            int k = 0;

            resultat.absolute(1);
            //vous positionner avant la première ligne de votre résultat
            resultat.beforeFirst();
            while (resultat.next()) {
                data[k][0] = resultat.getString("code");
                data[k][1] = resultat.getString("nom");
                data[k][2] = resultat.getString("institut");
                data[k][3] = resultat.getString("annee");
                data[k][4] = resultat.getString("semestre");

                k++;

            }

        } catch (SQLException e) {
        }
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_rechercher = new javax.swing.JTextField();
        Bouton_Rechercher = new javax.swing.JButton();
        labelUE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUE = new javax.swing.JTable(){
            public boolean isCellEditable(int d , int c){
                return false;
            }
        };
        moving2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 725));

        Bouton_Rechercher.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Bouton_Rechercher.setText("Rechercher");
        Bouton_Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_RechercherActionPerformed(evt);
            }
        });

        labelUE.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelUE.setText("UEs");

        TableUE.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TableUE.setGridColor(new java.awt.Color(255, 255, 255));
        TableUE.setRowHeight(22);
        TableUE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableUEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TableUEMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(TableUE);

        javax.swing.GroupLayout moving2Layout = new javax.swing.GroupLayout(moving2);
        moving2.setLayout(moving2Layout);
        moving2Layout.setHorizontalGroup(
            moving2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        moving2Layout.setVerticalGroup(
            moving2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(labelUE, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextField_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(Bouton_Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addComponent(moving2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(moving2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUE, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bouton_Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_RechercherActionPerformed
        // TODO add your handling code here:
        String query = "SELECT * FROM ue WHERE nomUE like ? OR codeUE like ? ";
        try {
            statement = conn.prepareStatement(query);
            String str = "%" + TextField_rechercher.getText() + "%";
            statement.setString(1, str);
            statement.setString(2, str);
        } catch (SQLException et) {
            System.out.println("Exception :" + et);
        }
        newAffichage(statement);
        /*try{
           
            String query = "SELECT * FROM ue WHERE nomUE like ? OR codeUE like ? ";
            sta = conn.prepareStatement(query);
            String str= "%"+TextField_rechercher.getText()+"%";
            sta.setString(1,str);
             sta.setString(2,str);
            rs = sta.executeQuery();
            TableUE.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            System.out.println("Exception :"+e);
        }*/

    }//GEN-LAST:event_Bouton_RechercherActionPerformed

    private void TableUEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUEMouseClicked
        // TODO add your handling code here:

        int count = evt.getClickCount();
        int row = TableUE.rowAtPoint(evt.getPoint());

        String matricule = TableUE.getValueAt(row, 0).toString();
        UesDAO dao = new UesDAO();
        UE ue;
        try {
            ue = dao.find(matricule);
            if (count >= 2) {//si on clique deux fois ça affichela page

                Chaque_UE shaq = new Chaque_UE(ue);
                Accueil.moving.add(shaq, "information");
                Accueil.card.show(Accueil.moving, "information");

            } else if (count == 1) {//si on clique une seule fois on récupère l'id pour supprimer
                del = ue;
            }

        } catch (SQLException e) {
            e.printStackTrace();

        }


    }//GEN-LAST:event_TableUEMouseClicked

    private void TableUEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUEMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_TableUEMouseEntered

    private void TableUEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUEMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_TableUEMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_Rechercher;
    private javax.swing.JTable TableUE;
    private javax.swing.JTextField TextField_rechercher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUE;
    public static javax.swing.JPanel moving2;
    // End of variables declaration//GEN-END:variables
}
