/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Carlos SMY
 */
public class Passerelle extends javax.swing.JPanel {

    /**
     * Creates new form Passerelle
     */
    public Passerelle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codeEcue4 = new javax.swing.JTextField();
        labelNomEcue1 = new javax.swing.JLabel();
        nomEcue3 = new javax.swing.JTextField();
        labelNomEcue4 = new javax.swing.JLabel();
        codeEcue3 = new javax.swing.JTextField();
        codeEcue2 = new javax.swing.JTextField();
        labelCodeEcue1 = new javax.swing.JLabel();
        codeEcue1 = new javax.swing.JTextField();
        codeUE = new javax.swing.JTextField();
        labelCodeEcue2 = new javax.swing.JLabel();
        nomEcue4 = new javax.swing.JTextField();
        labelCodeEcue3 = new javax.swing.JLabel();
        nomEcue1 = new javax.swing.JTextField();
        labelNom1 = new javax.swing.JLabel();
        labelCode1 = new javax.swing.JLabel();
        labelNomEcue2 = new javax.swing.JLabel();
        labelInstitu = new javax.swing.JLabel();
        nomUE = new javax.swing.JTextField();
        labelNomEcue3 = new javax.swing.JLabel();
        nomEcue2 = new javax.swing.JTextField();
        labelCodeEcue4 = new javax.swing.JLabel();
        labelAnnee = new javax.swing.JLabel();
        labelSemestre = new javax.swing.JLabel();
        semestre = new javax.swing.JComboBox<>();
        annee = new javax.swing.JComboBox<>();
        Institut = new javax.swing.JComboBox<>();
        ajout = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 1, 152));
        jLabel1.setText("Ajouter une UE");

        labelNomEcue1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNomEcue1.setText("Nom de l'Ecue 1");

        labelNomEcue4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNomEcue4.setText("Nom de l'Ecue 4");

        labelCodeEcue1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCodeEcue1.setText("Code de l'Ecue 1");

        labelCodeEcue2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCodeEcue2.setText("Code de l'Ecue 2");

        labelCodeEcue3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCodeEcue3.setText("Code de l'Ecue ");

        nomEcue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomEcue1ActionPerformed(evt);
            }
        });

        labelNom1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNom1.setText("Nom de l'UE");

        labelCode1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCode1.setText("Code de l'UE");

        labelNomEcue2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNomEcue2.setText("Nom de l'Ecue 2");

        labelInstitu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelInstitu.setText("Institut");

        nomUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUEActionPerformed(evt);
            }
        });

        labelNomEcue3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelNomEcue3.setText("Nom de l'Ecue 3");

        labelCodeEcue4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelCodeEcue4.setText("Code de l'Ecue 4");

        labelAnnee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelAnnee.setText("Année");

        labelSemestre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSemestre.setText("Semestre");

        semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        annee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Institut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Institut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstitutActionPerformed(evt);
            }
        });

        ajout.setText("Ajouter");
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCodeEcue1)
                                .addComponent(labelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNomEcue1))
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(codeEcue1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codeUE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomUE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomEcue1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCodeEcue2)
                                .addComponent(labelNomEcue2)
                                .addComponent(labelNomEcue3)
                                .addComponent(labelCodeEcue3))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomEcue3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codeEcue2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomEcue2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codeEcue3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNomEcue4)
                                .addComponent(labelCodeEcue4))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomEcue4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codeEcue4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelInstitu)
                                .addComponent(labelAnnee)
                                .addComponent(labelSemestre))
                            .addGap(126, 126, 126)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Institut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(jLabel1)))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeUE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomUE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCodeEcue1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeEcue1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNomEcue1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomEcue1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCodeEcue2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeEcue2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNomEcue2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomEcue2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCodeEcue3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeEcue3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNomEcue3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomEcue3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCodeEcue4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codeEcue4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNomEcue4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomEcue4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Institut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelInstitu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomEcue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomEcue1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomEcue1ActionPerformed

    private void nomUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUEActionPerformed

    private void InstitutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstitutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstitutActionPerformed

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ajoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Institut;
    private javax.swing.JButton ajout;
    private javax.swing.JComboBox<String> annee;
    private javax.swing.JTextField codeEcue1;
    private javax.swing.JTextField codeEcue2;
    private javax.swing.JTextField codeEcue3;
    private javax.swing.JTextField codeEcue4;
    private javax.swing.JTextField codeUE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAnnee;
    private javax.swing.JLabel labelCode1;
    private javax.swing.JLabel labelCodeEcue1;
    private javax.swing.JLabel labelCodeEcue2;
    private javax.swing.JLabel labelCodeEcue3;
    private javax.swing.JLabel labelCodeEcue4;
    private javax.swing.JLabel labelInstitu;
    private javax.swing.JLabel labelNom1;
    private javax.swing.JLabel labelNomEcue1;
    private javax.swing.JLabel labelNomEcue2;
    private javax.swing.JLabel labelNomEcue3;
    private javax.swing.JLabel labelNomEcue4;
    private javax.swing.JLabel labelSemestre;
    private javax.swing.JTextField nomEcue1;
    private javax.swing.JTextField nomEcue2;
    private javax.swing.JTextField nomEcue3;
    private javax.swing.JTextField nomEcue4;
    private javax.swing.JTextField nomUE;
    private javax.swing.JComboBox<String> semestre;
    // End of variables declaration//GEN-END:variables
}
